name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Theos 
      run: |
        mkdir theos
        git clone --depth=1 https://github.com/theos/theos.git theos
        export THEOS=$PWD/theos
      
        
    - name: Update Theos
      run: |
        cd theos
        git remote set-url origin https://github.com/theos/theos.git
        git config pull.rebase true
        git pull origin master
        git submodule update --init --recursive
        ls
    
    - name: Compile 
      run: |
        
        cd ../libSupport/demo
        make package

