name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Theos
      run: |
        git clone --depth=1 https://github.com/theos/theos.git
        export THEOS=$PWD/theos
    
    - name: Compile 
      run: |
        cd demo
        export THEOS=$PWD/theos
        make package

