name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Theos 
      run: |
        git remote set-url origin https://github.com/theos/theos.git
        git pull origin master
        git submodule update --init --recursive
        export THEOS=$PWD/theos
    
    - name: Compile 
      run: |
        export THEOS=$PWD/theos
        cd demo
        make package

