name: Compile iOS Framework to .dylib

on:
  push:
    branches: [ master ]

jobs:

  build-dylib:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: sinoru/actions-setup-xcode@v2.0.2
      with: 
       xcode-version: 15.0
      
    - name: Navigate to libSupport/demo
      run: |
        cd demo

    - name: Create project
      run: |
       xcodebuild -create-xcodeproj -project framework.xcodeproj -scheme framework


    - name: Install Xcode
      uses: mxcl/xcodebuild@v3.0.0
      with:
        working-directory: /Users/runner/work/libSupport/libSupport/demo
        action: build



    - name: Set Build Settings
      run: |
        xcodebuild -project framework.xcodeproj \
                   -target framework \
                   -c Release \
                   -settings \
                     "WRAPPER_EXTENSION=dylib" \
                     "MACH_O_TYPE=mutable_shared_library"
    
    - name: Build .dylib
      run: |
        xcodebuild -project framework.xcodeproj \
                   -target framework \
                   -c Release \
                   build
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: framework.dylib
        path: framework/Products/Release/framework.dylib
