name: Compile iOS Framework to .dylib

on:
  push:
    branches: [ master ]

jobs:

  build-dylib:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Navigate to libSupport/demo
      run: |
        cd demo

    - name: Install Xcode
      uses: mxcl/xcodebuild@v3.0.0
      with:
        action: build
        
    - name: Create Xcode Project
      run: |
        xcodebuild -create-xcodeproj -project framework.xcodeproj -scheme framework
    
    - name: Set Build Settings
      run: |
        xcodebuild -project framework.xcodeproj \
                   -target framework \
                   -c Release \
                   -settings \
                     "WRAPPER_EXTENSION=dylib" \
                     "MACH_O_TYPE=mutable_shared_library"
    
    - name: Build .dylib
      run: |
        xcodebuild -project framework.xcodeproj \
                   -target framework \
                   -c Release \
                   build
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: framework.dylib
        path: framework/Products/Release/framework.dylib
